version: '3.8'
services:
  kikoeru:
    image: mirrichwangd/kikoeru:latest
    container_name: kikoeru
    restart: unless-stopped
    build:
      context: ./
    ports:
      - '8888:8888'
    volumes:
      # Change the next line to your location of storage
      # e.g. /storage/DLsite/xxx:/usr/src/kikoeru/VoiceWork
      # Then fill in the location /usr/src/kikoeru/VoiceWork in the admin UI
      - ./VoiceWork:/usr/src/kikoeru/VoiceWork
      - ./sqlite:/usr/src/kikoeru/sqlite
      - ./covers:/usr/src/kikoeru/covers
      - ./config:/usr/src/kikoeru/config

